Add pytest to dev dependencies
cvs-health/langfair pull request #38
Opened 2024-11-15 13:12 UTC by virenbajaj

Add `pytest` version 8.3.3 (latest) to the `dev` group of dependencies in poetry. 

Note: If development and test dependencies increase and diverge, we could create a new dependency group for testing.  

Reference: https://python-poetry.org/docs/managing-dependencies/

2024-11-15 14:20 UTC, dylanbouchard commented
Thanks Viren! Can you please also include `pytest-asyncio`?

2024-11-15 14:41 UTC, dylanbouchard requested changes
Thanks Viren! Can you please also include `pytest-asyncio`?

2024-11-20 20:32 UTC, dylanbouchard commented on pyproject.toml
> +pytest-asyncio = "^0.24.0"
This should be under dev dependencies

2024-11-20 20:42 UTC, dylanbouchard approved these changes

2024-11-20 20:43 UTC, merged

2024-11-20 20:43 UTC, virenbajaj commented on pyproject.toml
> +pytest-asyncio = "^0.24.0"
Thanks for catching it - fixed